@extends('layouts.app')
@section('content')
@php
    $vehicleRows = collect($vehicles);
    $brandOptions = collect($brandOptions ?? $brands ?? $vehicleRows->map(fn ($vehicle) => data_get($vehicle, 'brand'))->filter()->unique('id')->sortBy('name'));
    $typeOptions = collect($typeOptions ?? $types ?? $vehicleRows->map(fn ($vehicle) => data_get($vehicle, 'type'))->filter()->unique('id')->sortBy('name'));
    // Prefer a future server-provided type catalog; otherwise use persisted associations
    // already present on the vehicle listing. Never invent options in the browser.
    $typeRows = $typeOptions->filter(fn ($type) => data_get($type, 'brand_id') && data_get($type, 'id'));
    $typeBrandMap = ($typeRows->isNotEmpty() ? $typeRows->groupBy(fn ($type) => (string) data_get($type, 'brand_id'))->map(fn ($rows) => $rows->pluck('id')) : $vehicleRows->filter(fn ($vehicle) => data_get($vehicle, 'brand_id') && data_get($vehicle, 'type_id'))
        ->groupBy(fn ($vehicle) => (string) data_get($vehicle, 'brand_id'))
        ->map(fn ($rows) => $rows->pluck('type_id')))
        ->map(fn ($ids) => $ids->map(fn ($id) => (string) $id)->unique()->values())
        ->toJson();
@endphp
<section class="master-data-panel" aria-labelledby="master-data-title"><div class="master-data-intro"><p class="eyebrow">MASTER DATA / 02</p><h2 id="master-data-title">Merk &amp; tipe</h2><p>Kelola pilihan kendaraan tanpa meninggalkan halaman armada.</p></div><div class="master-data-columns"><div class="master-data-card"><div class="master-card-heading"><h3>Merk kendaraan</h3><span>{{ $brandOptions->count() }} nilai</span></div><form method="POST" action="{{ route('brands.store') }}" class="master-add-form">@csrf<div class="inline-form"><label class="sr-only" for="new-brand-name">Tambah merk</label><input id="new-brand-name" name="name" maxlength="100" required placeholder="Contoh: Toyota"><button class="button button-primary" type="submit">Simpan</button></div>@error('name')<p class="field-error">{{ $message }}</p>@enderror</form><ul class="master-list" aria-label="Daftar merk">@forelse($brandOptions as $brand)<li><span>{{ $brand->name }}</span><button class="text-button" type="button" data-dialog-open="edit-brand-{{ $brand->id }}">Edit</button></li>@empty<li class="master-empty">Belum ada merk.</li>@endforelse</ul></div><div class="master-data-card"><div class="master-card-heading"><h3>Tipe kendaraan</h3><span>{{ $typeOptions->count() }} nilai</span></div><form method="POST" action="{{ route('types.store') }}" class="master-add-form">@csrf<div class="inline-form"><label class="sr-only" for="new-type-name">Tambah tipe</label><select id="new-type-brand" name="brand_id" required><option value="">Pilih merk</option>@foreach($brandOptions as $brand)<option value="{{ $brand->id }}">{{ $brand->name }}</option>@endforeach</select><input id="new-type-name" name="name" maxlength="100" required placeholder="Contoh: Avanza"><button class="button button-primary" type="submit">Simpan</button></div>@error('name')<p class="field-error">{{ $message }}</p>@enderror</form><ul class="master-list" aria-label="Daftar tipe">@forelse($typeOptions as $type)<li><span><strong>{{ $type->name }}</strong><small>{{ data_get($type, 'brand.name', 'Merk belum tersedia') }}</small></span><button class="text-button" type="button" data-dialog-open="edit-type-{{ $type->id }}">Edit</button></li>@empty<li class="master-empty">Belum ada tipe.</li>@endforelse</ul></div></div></section>
<div class="page-heading"><div><p class="eyebrow">MASTER DATA / 01</p><h1>Unit kendaraan <span class="heading-count">{{ method_exists($vehicles, 'total') ? $vehicles->total() : $vehicles->count() }}</span></h1><p class="lede">Kelola unit, tarif harian, dan ketersediaan armada.</p></div><button class="button button-primary" type="button" data-dialog-open="vehicle-form">+ Tambah unit</button></div>
<section class="toolbar-card" aria-label="Pencarian dan filter kendaraan"><form method="GET" class="filter-form"><div class="search-wrap"><span aria-hidden="true">⌕</span><label class="sr-only" for="vehicle-search">Cari plat nomor</label><input id="vehicle-search" name="search" value="{{ request('search') }}" placeholder="Cari plat nomor..."></div><label class="sr-only" for="vehicle-status">Filter status kendaraan</label><select id="vehicle-status" name="status"><option value="">Semua status</option><option value="active" @selected(request('status') === 'active')>Aktif</option><option value="archived" @selected(request('status') === 'archived')>Arsip</option></select><button class="button button-secondary" type="submit">Terapkan filter</button></form></section>
<section class="table-card"><div class="table-header"><div><h2>Semua unit</h2><p>Inventaris armada terdaftar</p></div><span class="table-note">Data terbarui otomatis</span></div><div class="table-scroll"><table><thead><tr><th>Unit</th><th>Plat nomor</th><th>Tarif / hari</th><th>Status</th><th><span class="sr-only">Aksi</span></th></tr></thead><tbody>@forelse($vehicles as $vehicle)<tr><td><strong>{{ data_get($vehicle, 'brand.name', '—') }}</strong><small>{{ data_get($vehicle, 'type.name', 'Tipe belum tersedia') }}</small></td><td><span class="plate-code">{{ $vehicle->plate }}</span></td><td>${{ number_format(($vehicle->daily_rate_cents ?? 0) / 100, 2) }}</td><td><span class="status-pill {{ data_get($vehicle, 'derived_status') === 'tersedia' ? 'status-available' : ($vehicle->archived_at ? 'status-archived' : 'status-rented') }}"><span></span>{{ ucfirst(str_replace('-', ' ', data_get($vehicle, 'derived_status', $vehicle->archived_at ? 'arsip' : 'tersedia'))) }}</span></td><td class="row-actions"><button class="text-button" type="button" data-dialog-open="edit-vehicle-{{ $vehicle->id }}">Edit</button>@if($vehicle->archived_at)<button class="text-button" type="button" data-dialog-open="restore-vehicle-{{ $vehicle->id }}">Pulihkan</button>@else<button class="text-button text-danger" type="button" data-dialog-open="archive-vehicle-{{ $vehicle->id }}">Arsipkan</button>@endif</td></tr>@empty<tr><td colspan="5" class="empty-state">Belum ada unit kendaraan yang sesuai.</td></tr>@endforelse</tbody></table></div><div class="pagination-row">{{ $vehicles->links() }}</div></section>

<div class="dialog" id="vehicle-form" role="dialog" aria-modal="true" aria-labelledby="vehicle-form-title" hidden><div class="dialog-card"><button class="dialog-close" type="button" data-dialog-close aria-label="Tutup">×</button><p class="eyebrow">UNIT BARU</p><h2 id="vehicle-form-title">Tambah unit kendaraan</h2><p class="dialog-lede">Isi detail dasar unit untuk menambahkannya ke armada aktif.</p><form method="POST" action="{{ url('/vehicles') }}" class="stack-form" data-brand-type-form data-type-brand-map='@json(json_decode($typeBrandMap, true))'>@csrf<div class="form-grid"><div class="field-group"><label for="brand_id">Merk</label><select id="brand_id" name="brand_id" required data-brand-select><option value="">Pilih merk</option>@foreach($brandOptions as $brand)<option value="{{ $brand->id }}" @selected((string)old('brand_id') === (string)$brand->id)>{{ $brand->name }}</option>@endforeach</select>@error('brand_id')<p class="field-error" id="brand_id-error">{{ $message }}</p>@enderror</div><div class="field-group"><label for="type_id">Tipe</label><select id="type_id" name="type_id" required disabled data-type-select data-initial-value="{{ old('type_id') }}" aria-describedby="type_id-help"><option value="">Pilih merk terlebih dahulu</option>@foreach($typeOptions as $type)<option value="{{ $type->id }}" data-type-id="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select><p class="field-help" id="type_id-help">Pilih merk untuk melihat tipe yang sesuai.</p>@error('type_id')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field-group"><label for="plate">Plat nomor</label><input id="plate" name="plate" value="{{ old('plate') }}" required>@error('plate')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field-group"><label for="daily_rate_cents">Tarif harian (USD cents)</label><input id="daily_rate_cents" name="daily_rate_cents" type="number" min="1" value="{{ old('daily_rate_cents') }}" required>@error('daily_rate_cents')<p class="field-error">{{ $message }}</p>@enderror</div></div><button class="button button-primary" type="submit">Simpan unit <span>↗</span></button></form></div></div>
@foreach($vehicles as $vehicle)
<div class="dialog" id="edit-vehicle-{{ $vehicle->id }}" role="dialog" aria-modal="true" aria-labelledby="edit-vehicle-title-{{ $vehicle->id }}" hidden><div class="dialog-card"><button class="dialog-close" type="button" data-dialog-close aria-label="Tutup">×</button><p class="eyebrow">UNIT / EDIT</p><h2 id="edit-vehicle-title-{{ $vehicle->id }}">Edit unit kendaraan</h2><form method="POST" action="{{ url('/vehicles/'.$vehicle->id) }}" class="stack-form" data-brand-type-form data-type-brand-map='@json(json_decode($typeBrandMap, true))'>@csrf @method('PUT')<div class="form-grid"><div class="field-group"><label for="edit-brand-{{ $vehicle->id }}">Merk</label><select id="edit-brand-{{ $vehicle->id }}" name="brand_id" required data-brand-select>@foreach($brandOptions as $brand)<option value="{{ $brand->id }}" @selected((string)data_get($vehicle, 'brand_id') === (string)$brand->id)>{{ $brand->name }}</option>@endforeach</select>@error('brand_id')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field-group"><label for="edit-type-{{ $vehicle->id }}">Tipe</label><select id="edit-type-{{ $vehicle->id }}" name="type_id" required data-type-select data-initial-value="{{ data_get($vehicle, 'type_id') }}" disabled aria-describedby="edit-type-help-{{ $vehicle->id }}"><option value="">Pilih merk terlebih dahulu</option>@foreach($typeOptions as $type)<option value="{{ $type->id }}" data-type-id="{{ $type->id }}">{{ $type->name }}</option>@endforeach</select><p class="field-help" id="edit-type-help-{{ $vehicle->id }}">Tipe saat ini dipertahankan sampai merk diubah.</p>@error('type_id')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field-group"><label for="edit-plate-{{ $vehicle->id }}">Plat nomor</label><input id="edit-plate-{{ $vehicle->id }}" name="plate" value="{{ $vehicle->plate }}" required>@error('plate')<p class="field-error">{{ $message }}</p>@enderror</div><div class="field-group"><label for="edit-rate-{{ $vehicle->id }}">Tarif harian (USD cents)</label><input id="edit-rate-{{ $vehicle->id }}" name="daily_rate_cents" type="number" min="1" value="{{ $vehicle->daily_rate_cents }}" required>@error('daily_rate_cents')<p class="field-error">{{ $message }}</p>@enderror</div></div><button class="button button-primary" type="submit">Simpan perubahan</button></form></div></div>
@if($vehicle->archived_at)<div class="dialog" id="restore-vehicle-{{ $vehicle->id }}" role="dialog" aria-modal="true" aria-labelledby="restore-title-{{ $vehicle->id }}" hidden><div class="dialog-card"><button class="dialog-close" type="button" data-dialog-close aria-label="Tutup">×</button><p class="eyebrow">CONFIRM ACTION</p><h2 id="restore-title-{{ $vehicle->id }}">Pulihkan unit ini?</h2><p class="dialog-lede">Unit akan kembali masuk ke daftar armada aktif.</p><form method="POST" action="{{ url('/vehicles/'.$vehicle->id.'/restore') }}">@csrf<label class="confirm-check"><input type="checkbox" name="confirmed" value="1" required> Saya mengonfirmasi pemulihan unit ini.</label><button class="button button-primary" type="submit">Konfirmasi pulihkan</button></form></div></div>@else<div class="dialog" id="archive-vehicle-{{ $vehicle->id }}" role="dialog" aria-modal="true" aria-labelledby="archive-title-{{ $vehicle->id }}" hidden><div class="dialog-card"><button class="dialog-close" type="button" data-dialog-close aria-label="Tutup">×</button><p class="eyebrow">CONFIRM ACTION</p><h2 id="archive-title-{{ $vehicle->id }}">Arsipkan unit ini?</h2><p class="dialog-lede">Riwayat tetap tersimpan, tetapi unit tidak dapat digunakan untuk rental baru.</p><form method="POST" action="{{ url('/vehicles/'.$vehicle->id.'/archive') }}">@csrf<label class="confirm-check"><input type="checkbox" name="confirmed" value="1" required> Saya mengonfirmasi pengarsipan unit ini.</label><button class="button button-primary" type="submit">Konfirmasi arsipkan</button></form></div></div>@endif
@endforeach
@foreach($brandOptions as $brand)<div class="dialog" id="edit-brand-{{ $brand->id }}" role="dialog" aria-modal="true" aria-labelledby="edit-brand-title-{{ $brand->id }}" hidden><div class="dialog-card"><button class="dialog-close" type="button" data-dialog-close aria-label="Tutup">×</button><p class="eyebrow">MERK / EDIT</p><h2 id="edit-brand-title-{{ $brand->id }}">Edit merk kendaraan</h2><form method="POST" action="{{ route('brands.update', $brand->id) }}" class="stack-form">@csrf @method('PUT')<div class="field-group"><label for="brand-name-{{ $brand->id }}">Nama merk</label><input id="brand-name-{{ $brand->id }}" name="name" value="{{ $brand->name }}" maxlength="100" required></div><button class="button button-primary" type="submit">Simpan perubahan</button></form></div></div>@endforeach
@foreach($typeOptions as $type)<div class="dialog" id="edit-type-{{ $type->id }}" role="dialog" aria-modal="true" aria-labelledby="edit-type-title-{{ $type->id }}" hidden><div class="dialog-card"><button class="dialog-close" type="button" data-dialog-close aria-label="Tutup">×</button><p class="eyebrow">TIPE / EDIT</p><h2 id="edit-type-title-{{ $type->id }}">Edit tipe kendaraan</h2><form method="POST" action="{{ route('types.update', $type->id) }}" class="stack-form">@csrf @method('PUT')<div class="field-group"><label for="type-brand-{{ $type->id }}">Merk induk</label><select id="type-brand-{{ $type->id }}" name="brand_id" required>@foreach($brandOptions as $brand)<option value="{{ $brand->id }}" @selected((string)data_get($type, 'brand_id') === (string)$brand->id)>{{ $brand->name }}</option>@endforeach</select></div><div class="field-group"><label for="type-name-{{ $type->id }}">Nama tipe</label><input id="type-name-{{ $type->id }}" name="name" value="{{ $type->name }}" maxlength="100" required></div><button class="button button-primary" type="submit">Simpan perubahan</button></form></div></div>@endforeach
@endsection
