@extends('layouts.app')
@section('content')
@php
    $item = $rental ?? null;
@endphp
@php
    $startDate = data_get($item, 'start_date');
    $endDate = data_get($item, 'end_date');
    $durationDays = $startDate && $endDate ? $startDate->diffInDays($endDate) + 1 : 0;
    $dateInputValue = static function ($date): string {
        if ($date instanceof \DateTimeInterface) {
            return $date->format('Y-m-d');
        }

        $parsed = is_string($date) ? date_create($date) : false;

        return $parsed ? $parsed->format('Y-m-d') : '';
    };
    $startDateInput = $dateInputValue(old('start_date', $startDate));
    $endDateInput = $dateInputValue(old('end_date', $endDate));
@endphp
<div class="page-heading"><div><p class="eyebrow">RENTAL / DETAIL</p><h1>Rental #{{ data_get($item, 'id', '—') }}</h1><p class="lede">Ringkasan perjalanan dan jejak lifecycle yang dapat diaudit.</p></div><a class="button button-secondary" href="{{ route('rentals.index') }}">← Kembali</a></div>
<section class="detail-grid"><article class="table-card detail-card"><div class="table-header"><div><h2>{{ data_get($item, 'vehicle.plate', 'Unit belum ditentukan') }}</h2><p>{{ data_get($item, 'customer.name', 'Pelanggan belum ditentukan') }}</p></div><span class="status-pill status-{{ data_get($item, 'status', 'booked') }}"><span></span>{{ ucfirst(data_get($item, 'status', 'booked')) }}</span></div><dl class="detail-list"><div><dt>Mulai</dt><dd>@if($startDate)<x-rental-date :date="$startDate" />@else—@endif</dd></div><div><dt>Selesai</dt><dd>@if($endDate)<x-rental-date :date="$endDate" :end-of-day="true" />@else—@endif</dd></div><div><dt>Tarif harian (snapshot)</dt><dd>${{ number_format(data_get($item, 'daily_rate_snapshot_cents', 0) / 100, 2) }} / hari</dd></div><div><dt>Durasi</dt><dd>{{ $durationDays }} hari</dd></div><div><dt>Subtotal</dt><dd>${{ number_format(data_get($item, 'subtotal_cents', 0) / 100, 2) }}</dd></div><div><dt>Diskon</dt><dd>-${{ number_format(data_get($item, 'discount_cents', 0) / 100, 2) }}</dd></div><div><dt>Total</dt><dd class="detail-total">${{ number_format(data_get($item, 'total_cents', 0) / 100, 2) }}</dd></div></dl></article><aside class="action-card"><button class="button button-primary" type="button" data-dialog-open="cancel-rental">Batalkan rental</button><form method="POST" action="{{ route('rentals.complete', ['rental' => data_get($item, 'id')]) }}">@csrf<button class="button button-secondary" type="submit">Tandai selesai</button></form><a class="text-button" href="{{ route('rentals.history', ['rental' => data_get($item, 'id')]) }}">Lihat lifecycle history ↗</a></aside></section>
<div class="dialog" id="cancel-rental" role="dialog" aria-modal="true" aria-labelledby="cancel-title" hidden><div class="dialog-card"><button class="dialog-close" type="button" data-dialog-close aria-label="Tutup">×</button><p class="eyebrow">CONFIRM ACTION</p><h2 id="cancel-title">Batalkan rental ini?</h2><p class="dialog-lede">Pembatalan membutuhkan alasan dan akan dicatat pada lifecycle history.</p><form method="POST" action="{{ route('rentals.cancel', ['rental' => data_get($item, 'id')]) }}" class="stack-form">@csrf<label class="field-group" for="reason">Alasan pembatalan<textarea id="reason" name="reason" rows="4" required>{{ old('reason') }}</textarea></label><button class="button button-primary" type="submit">Konfirmasi pembatalan</button></form></div></div>
<section class="table-card history-preview"><div class="table-header"><div><h2>Lifecycle history</h2><p>Perubahan status rental</p></div></div><div class="timeline">@forelse(($history ?? []) as $event)<div><span class="timeline-dot"></span><strong>{{ ucfirst(str_replace('_', ' ', $event->event_type ?? 'event')) }}</strong><small>{{ $event->occurred_at ?? '—' }} · {{ $event->reason ?? '' }}</small></div>@empty<p class="empty-state">History belum tersedia.</p>@endforelse</div></section>
@php($rentalStatus = data_get($item, 'status', 'booked'))
<section class="form-card edit-rental-card"><div><p class="eyebrow">EDIT RESERVATION</p><h2>Perbarui rental</h2><p class="dialog-lede">{{ $rentalStatus === 'active' ? 'Rental active hanya dapat mengubah tanggal selesai.' : 'Rental booked dapat diubah penuh sebelum disimpan kembali.' }}</p></div><form method="POST" action="{{ route('rentals.update', ['rental' => data_get($item, 'id')]) }}" class="stack-form">@csrf @method('PUT')<div class="form-grid">@if($rentalStatus !== 'active')<div class="field-group"><label for="edit_vehicle_id">Kendaraan</label><select id="edit_vehicle_id" name="vehicle_id" required>@foreach(($vehicles ?? []) as $vehicle)<option value="{{ $vehicle->id }}" @selected((string)data_get($item, 'vehicle_id') === (string)$vehicle->id)>{{ $vehicle->plate }}</option>@endforeach</select></div><div class="field-group"><label for="edit_customer_id">Pelanggan</label><select id="edit_customer_id" name="customer_id" required>@foreach(($customers ?? []) as $customer)<option value="{{ $customer->id }}" @selected((string)data_get($item, 'customer_id') === (string)$customer->id)>{{ $customer->name }}</option>@endforeach</select></div><div class="field-group"><label for="edit_start_date">Mulai</label><input id="edit_start_date" name="start_date" type="date" value="{{ $startDateInput }}" required></div>@else<input type="hidden" name="vehicle_id" value="{{ data_get($item, 'vehicle_id') }}"><input type="hidden" name="customer_id" value="{{ data_get($item, 'customer_id') }}"><input type="hidden" name="start_date" value="{{ $startDateInput }}">@endif<div class="field-group"><label for="edit_end_date">Selesai</label><input id="edit_end_date" name="end_date" type="date" value="{{ $endDateInput }}" required></div></div><button class="button button-secondary" type="submit">Simpan perubahan ↗</button></form></section>
@endsection
